// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Methods_of_artificial_intelligence_systemsML.Model
{
    public class ModelInput
    {
        // 0 - ball
        // 1 - small ball
        // 2 - volanchyk
        // 3 - figures
        [ColumnName("col0"), LoadColumn(0)]
        public float Item { get; set; }

        // Count of players
        [ColumnName("col1"), LoadColumn(1)]
        public float PlayersCount { get; set; }

        // 0 - yes
        // 1 - no
        [ColumnName("col2"), LoadColumn(2)]
        public float Comand { get; set; }

        // 0 - big
        // 1 - medium
        // 2 - small
        // 3 - none
        // 4 - table
        [ColumnName("col3"), LoadColumn(3)]
        public float AreaSize { get; set; }

        // 0 - yes
        // 1 - no
        [ColumnName("col4"), LoadColumn(4)]
        public float Net { get; set; }

        // Label
        [ColumnName("col5"), LoadColumn(5)]
        public string Label { get; set; }
    }
}
